---
- name: Install node_exporter
  hosts: all
  gather_facts: true
  become: true
  vars_files:
    - vars/vars_vault.yaml
    - vars/package_urls.yaml
  vars:
    nodeexporter_local_tar: "/opt/{{ nodeexporter_url | basename }}"
    nodeexporter_dir: "/opt/{{ nodeexporter_url[:-7] | basename }}"
  tasks:
    - name: Print nodeexporter_url
      debug:
        msg: "{{ nodeexporter_url }}"
        verbosity: 1
    - name: Print nodeexporter_local_tar
      debug:
        msg: "{{ nodeexporter_local_tar }}"
        verbosity: 1
    - name: Print nodeexporter_dir
      debug:
        msg: "{{ nodeexporter_dir }}"
        verbosity: 1

    - name: Disable firewalld
      ansible.builtin.service:
        name: firewalld
        state: stopped
        enabled: false
    - name: Add node_exporter firewall port
      ansible.posix.firewalld:
        port: 10100/tcp
        permanent: true
        state: enabled
    - name: Include install-node-exporter
      ansible.builtin.include_role:
        name: setup-gpdashboard
        tasks_from: install-node-exporter.yaml
