---
- name: Install Prometheus, Grafana, and node_exporter
  hosts: all
  gather_facts: true
  become: true
  vars_files:
    - vars/vars_vault.yaml
    - vars/package_urls.yaml
  vars:
    prometheus_local_tar: "/opt/{{ prometheus_url | basename }}"
    prometheus_dir: "/opt/{{ prometheus_url[:-7] | basename }}"
    nodeexporter_local_tar: "/opt/{{ nodeexporter_url | basename }}"
    nodeexporter_dir: "/opt/{{ nodeexporter_url[:-7] | basename }}"
  tasks:
    - name: Print prometheus_url
      debug:
        msg: "{{ prometheus_url }}"
        verbosity: 1
    - name: Print prometheus_local_tar
      debug:
        msg: "{{ prometheus_local_tar }}"
        verbosity: 1
    - name: Print prometheus_dir
      debug:
        msg: "{{ prometheus_dir }}"
        verbosity: 1
    - name: Print nodeexporter_url
      debug:
        msg: "{{ nodeexporter_url }}"
        verbosity: 1
    - name: Print nodeexporter_local_tar
      debug:
        msg: "{{ nodeexporter_local_tar }}"
        verbosity: 1
    - name: Print nodeexporter_dir
      debug:
        msg: "{{ nodeexporter_dir }}"
        verbosity: 1

    - name: Disable firewalld
      ansible.builtin.service:
        name: firewalld
        state: stopped
        enabled: false
    # Cockpit and Prometheus use port 9090 by default.
    # Prometheus has been configured to use port 10090.
    - name: Disable cockpit.service
      ansible.builtin.systemd:
        name: cockpit.service
        state: stopped
        enabled: false
      failed_when: false
    - name: Disable cockpit.socket
      ansible.builtin.systemd:
        name: cockpit.socket
        state: stopped
        enabled: false
      failed_when: false
    - name: Include install-node-exporter
      ansible.builtin.include_role:
        name: setup-gpdashboard
        tasks_from: install-node-exporter.yaml
    - name: Include install-prometheus
      ansible.builtin.include_role:
        name: setup-gpdashboard
        tasks_from: install-prometheus.yaml
    - name: Include install-grafana
      ansible.builtin.include_role:
        name: setup-gpdashboard
        tasks_from: install-grafana.yaml
